### ISSUE TITLE
src/fetch_datasets.py integrated into toolbox, but still mentioned in docs

### ISSUE THREAD

**Issue by cauebs** [datasciencebr/serenata-de-amor#222] opened 2017-04-29 12:37 UTC
The contribution guide still points to `src/fetch_datasets.py`, which was removed in 1604567f55c782874e9ee98f979f98cd3ab76d60. I'll be opening a pull request soon recreating the file, now containing just these two lines:

```python
from serenata_toolbox.datasets import fetch_latest_backup
fetch_latest_backup('data/')
```

This way, the `setup` file can be changed to a bash script, only invoking python to run this new file on the last lines.

**Comment by anaschwendler** [comment] 2017-11-30 13:02
The issue is already solved, so I'll close it for now.

**Closed by anaschwendler** 2017-11-30 13:02 UTC
Labels: documentation, enhancement
